/**
 * Centralized permission catalog for the ERP platform.
 *
 * Organized by domain. Each key maps to a dot-notation string
 * that is stored in the Permission table per tenant.
 *
 * Tenants can create custom permissions, but these platform
 * defaults are seeded on tenant creation.
 */
export const PERMISSIONS = {
  // ─── Auth & Identity ────────────────────────────────────────────────
  AUTH_USERS_READ: 'auth.users.read',
  AUTH_USERS_MANAGE: 'auth.users.manage',
  AUTH_ROLES_READ: 'auth.roles.read',
  AUTH_ROLES_MANAGE: 'auth.roles.manage',
  AUTH_PERMISSIONS_READ: 'auth.permissions.read',
  AUTH_PERMISSIONS_MANAGE: 'auth.permissions.manage',

  // ─── Accounting ─────────────────────────────────────────────────────
  ACCOUNTING_COA_READ: 'accounting.coa.read',
  ACCOUNTING_COA_WRITE: 'accounting.coa.write',
  ACCOUNTING_JOURNAL_READ: 'accounting.journal.read',
  ACCOUNTING_JOURNAL_WRITE: 'accounting.journal.write',
  ACCOUNTING_JOURNAL_POST: 'accounting.journal.post',
  ACCOUNTING_JOURNAL_REVERSE: 'accounting.journal.reverse',
  ACCOUNTING_PERIOD_READ: 'accounting.period.read',
  ACCOUNTING_PERIOD_MANAGE: 'accounting.period.manage',
  ACCOUNTING_REPORTS_READ: 'accounting.reports.read',
  ACCOUNTING_REPORTS_EXPORT: 'accounting.reports.export',
  ACCOUNTING_BUDGET_READ: 'accounting.budget.read',
  ACCOUNTING_BUDGET_MANAGE: 'accounting.budget.manage',

  // ─── Business Documents ─────────────────────────────────────────────
  BUSINESS_CONTACTS_READ: 'business.contacts.read',
  BUSINESS_CONTACTS_MANAGE: 'business.contacts.manage',
  BUSINESS_INVOICES_READ: 'business.invoices.read',
  BUSINESS_INVOICES_MANAGE: 'business.invoices.manage',
  BUSINESS_INVOICES_APPROVE: 'business.invoices.approve',
  BUSINESS_PAYMENTS_READ: 'business.payments.read',
  BUSINESS_PAYMENTS_MANAGE: 'business.payments.manage',
  BUSINESS_PAYMENTS_APPROVE: 'business.payments.approve',

  // ─── Compliance ─────────────────────────────────────────────────────
  COMPLIANCE_VAT_READ: 'compliance.vat.read',
  COMPLIANCE_VAT_MANAGE: 'compliance.vat.manage',
  COMPLIANCE_ZATCA_READ: 'compliance.zatca.read',
  COMPLIANCE_ZATCA_MANAGE: 'compliance.zatca.manage',
  COMPLIANCE_ZAKAT_READ: 'compliance.zakat.read',
  COMPLIANCE_ZAKAT_MANAGE: 'compliance.zakat.manage',
  COMPLIANCE_WHT_READ: 'compliance.wht.read',
  COMPLIANCE_WHT_MANAGE: 'compliance.wht.manage',
  COMPLIANCE_GOSI_READ: 'compliance.gosi.read',
  COMPLIANCE_GOSI_MANAGE: 'compliance.gosi.manage',
  COMPLIANCE_WPS_READ: 'compliance.wps.read',
  COMPLIANCE_WPS_MANAGE: 'compliance.wps.manage',

  // ─── Administration ─────────────────────────────────────────────────
  ADMIN_TENANT_READ: 'admin.tenant.read',
  ADMIN_TENANT_MANAGE: 'admin.tenant.manage',
  ADMIN_AUDIT_READ: 'admin.audit.read',
  ADMIN_SETTINGS_READ: 'admin.settings.read',
  ADMIN_SETTINGS_MANAGE: 'admin.settings.manage',
  ADMIN_BRANCHES_READ: 'admin.branches.read',
  ADMIN_BRANCHES_MANAGE: 'admin.branches.manage',
  ADMIN_COST_CENTERS_READ: 'admin.costcenters.read',
  ADMIN_COST_CENTERS_MANAGE: 'admin.costcenters.manage',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/** All permission keys as a flat array, used for seeding. */
export const ALL_PERMISSION_KEYS: PermissionKey[] = Object.values(PERMISSIONS);

/**
 * Human-readable descriptions for each permission.
 * Used when seeding the Permission table.
 */
export const PERMISSION_DESCRIPTIONS: Record<PermissionKey, string> = {
  [PERMISSIONS.AUTH_USERS_READ]: 'View user accounts within the tenant',
  [PERMISSIONS.AUTH_USERS_MANAGE]: 'Create, update, disable, and invite users',
  [PERMISSIONS.AUTH_ROLES_READ]: 'View roles and their assigned permissions',
  [PERMISSIONS.AUTH_ROLES_MANAGE]: 'Create, update, and delete roles',
  [PERMISSIONS.AUTH_PERMISSIONS_READ]: 'View the permission catalog',
  [PERMISSIONS.AUTH_PERMISSIONS_MANAGE]: 'Create and manage custom permissions',
  [PERMISSIONS.ACCOUNTING_COA_READ]: 'View the chart of accounts',
  [PERMISSIONS.ACCOUNTING_COA_WRITE]: 'Create and modify accounts',
  [PERMISSIONS.ACCOUNTING_JOURNAL_READ]: 'View journal entries',
  [PERMISSIONS.ACCOUNTING_JOURNAL_WRITE]: 'Create and edit draft journal entries',
  [PERMISSIONS.ACCOUNTING_JOURNAL_POST]: 'Post journal entries to the ledger',
  [PERMISSIONS.ACCOUNTING_JOURNAL_REVERSE]: 'Reverse posted journal entries',
  [PERMISSIONS.ACCOUNTING_PERIOD_READ]: 'View accounting periods',
  [PERMISSIONS.ACCOUNTING_PERIOD_MANAGE]: 'Open, close, and reopen accounting periods',
  [PERMISSIONS.ACCOUNTING_REPORTS_READ]: 'View financial reports and statements',
  [PERMISSIONS.ACCOUNTING_REPORTS_EXPORT]: 'Export financial reports',
  [PERMISSIONS.ACCOUNTING_BUDGET_READ]: 'View budgets',
  [PERMISSIONS.ACCOUNTING_BUDGET_MANAGE]: 'Create and manage budgets',
  [PERMISSIONS.BUSINESS_CONTACTS_READ]: 'View customers and suppliers',
  [PERMISSIONS.BUSINESS_CONTACTS_MANAGE]: 'Create and manage contacts',
  [PERMISSIONS.BUSINESS_INVOICES_READ]: 'View sales and purchase invoices',
  [PERMISSIONS.BUSINESS_INVOICES_MANAGE]: 'Create and edit draft invoices',
  [PERMISSIONS.BUSINESS_INVOICES_APPROVE]: 'Approve invoices and generate journal entries',
  [PERMISSIONS.BUSINESS_PAYMENTS_READ]: 'View payments and receipts',
  [PERMISSIONS.BUSINESS_PAYMENTS_MANAGE]: 'Create and edit draft payments',
  [PERMISSIONS.BUSINESS_PAYMENTS_APPROVE]: 'Approve payments and generate journal entries',
  [PERMISSIONS.COMPLIANCE_VAT_READ]: 'View VAT configuration and returns',
  [PERMISSIONS.COMPLIANCE_VAT_MANAGE]: 'Configure VAT rates and file returns',
  [PERMISSIONS.COMPLIANCE_ZATCA_READ]: 'View ZATCA e-invoicing status',
  [PERMISSIONS.COMPLIANCE_ZATCA_MANAGE]: 'Manage ZATCA integration and submission',
  [PERMISSIONS.COMPLIANCE_ZAKAT_READ]: 'View Zakat calculations',
  [PERMISSIONS.COMPLIANCE_ZAKAT_MANAGE]: 'Manage Zakat reporting',
  [PERMISSIONS.COMPLIANCE_WHT_READ]: 'View withholding tax records',
  [PERMISSIONS.COMPLIANCE_WHT_MANAGE]: 'Manage withholding tax configuration',
  [PERMISSIONS.COMPLIANCE_GOSI_READ]: 'View GOSI contribution data',
  [PERMISSIONS.COMPLIANCE_GOSI_MANAGE]: 'Manage GOSI integration',
  [PERMISSIONS.COMPLIANCE_WPS_READ]: 'View WPS/Mudad salary files',
  [PERMISSIONS.COMPLIANCE_WPS_MANAGE]: 'Manage WPS/Mudad salary submissions',
  [PERMISSIONS.ADMIN_TENANT_READ]: 'View tenant profile and settings',
  [PERMISSIONS.ADMIN_TENANT_MANAGE]: 'Manage tenant profile, billing, and status',
  [PERMISSIONS.ADMIN_AUDIT_READ]: 'View audit logs',
  [PERMISSIONS.ADMIN_SETTINGS_READ]: 'View platform and tenant settings',
  [PERMISSIONS.ADMIN_SETTINGS_MANAGE]: 'Modify platform and tenant settings',
  [PERMISSIONS.ADMIN_BRANCHES_READ]: 'View branches',
  [PERMISSIONS.ADMIN_BRANCHES_MANAGE]: 'Create and manage branches',
  [PERMISSIONS.ADMIN_COST_CENTERS_READ]: 'View cost centers',
  [PERMISSIONS.ADMIN_COST_CENTERS_MANAGE]: 'Create and manage cost centers',
};

/**
 * Default role templates seeded on tenant creation.
 * isSystemRole = true prevents deletion by tenant admins.
 */
export const DEFAULT_ROLES = {
  OWNER: {
    name: 'Owner',
    description: 'Full access to all tenant resources. Cannot be deleted.',
    permissions: ALL_PERMISSION_KEYS,
  },
  ADMIN: {
    name: 'Admin',
    description: 'Administrative access to manage users, roles, and settings.',
    permissions: [
      PERMISSIONS.AUTH_USERS_READ,
      PERMISSIONS.AUTH_USERS_MANAGE,
      PERMISSIONS.AUTH_ROLES_READ,
      PERMISSIONS.AUTH_ROLES_MANAGE,
      PERMISSIONS.AUTH_PERMISSIONS_READ,
      PERMISSIONS.ACCOUNTING_COA_READ,
      PERMISSIONS.ACCOUNTING_COA_WRITE,
      PERMISSIONS.ACCOUNTING_JOURNAL_READ,
      PERMISSIONS.ACCOUNTING_JOURNAL_WRITE,
      PERMISSIONS.ACCOUNTING_JOURNAL_POST,
      PERMISSIONS.ACCOUNTING_PERIOD_READ,
      PERMISSIONS.ACCOUNTING_PERIOD_MANAGE,
      PERMISSIONS.ACCOUNTING_REPORTS_READ,
      PERMISSIONS.ACCOUNTING_REPORTS_EXPORT,
      PERMISSIONS.ACCOUNTING_BUDGET_READ,
      PERMISSIONS.ACCOUNTING_BUDGET_MANAGE,
      PERMISSIONS.BUSINESS_CONTACTS_READ,
      PERMISSIONS.BUSINESS_CONTACTS_MANAGE,
      PERMISSIONS.BUSINESS_INVOICES_READ,
      PERMISSIONS.BUSINESS_INVOICES_MANAGE,
      PERMISSIONS.BUSINESS_INVOICES_APPROVE,
      PERMISSIONS.BUSINESS_PAYMENTS_READ,
      PERMISSIONS.BUSINESS_PAYMENTS_MANAGE,
      PERMISSIONS.BUSINESS_PAYMENTS_APPROVE,
      PERMISSIONS.COMPLIANCE_VAT_READ,
      PERMISSIONS.COMPLIANCE_VAT_MANAGE,
      PERMISSIONS.COMPLIANCE_ZATCA_READ,
      PERMISSIONS.COMPLIANCE_ZATCA_MANAGE,
      PERMISSIONS.COMPLIANCE_ZAKAT_READ,
      PERMISSIONS.COMPLIANCE_ZAKAT_MANAGE,
      PERMISSIONS.COMPLIANCE_WHT_READ,
      PERMISSIONS.COMPLIANCE_WHT_MANAGE,
      PERMISSIONS.COMPLIANCE_GOSI_READ,
      PERMISSIONS.COMPLIANCE_GOSI_MANAGE,
      PERMISSIONS.COMPLIANCE_WPS_READ,
      PERMISSIONS.COMPLIANCE_WPS_MANAGE,
      PERMISSIONS.ADMIN_TENANT_READ,
      PERMISSIONS.ADMIN_AUDIT_READ,
      PERMISSIONS.ADMIN_SETTINGS_READ,
      PERMISSIONS.ADMIN_SETTINGS_MANAGE,
      PERMISSIONS.ADMIN_BRANCHES_READ,
      PERMISSIONS.ADMIN_BRANCHES_MANAGE,
      PERMISSIONS.ADMIN_COST_CENTERS_READ,
      PERMISSIONS.ADMIN_COST_CENTERS_MANAGE,
    ],
  },
  ACCOUNTANT: {
    name: 'Accountant',
    description: 'Full access to accounting, reports, and compliance modules.',
    permissions: [
      PERMISSIONS.ACCOUNTING_COA_READ,
      PERMISSIONS.ACCOUNTING_COA_WRITE,
      PERMISSIONS.ACCOUNTING_JOURNAL_READ,
      PERMISSIONS.ACCOUNTING_JOURNAL_WRITE,
      PERMISSIONS.ACCOUNTING_JOURNAL_POST,
      PERMISSIONS.ACCOUNTING_JOURNAL_REVERSE,
      PERMISSIONS.ACCOUNTING_PERIOD_READ,
      PERMISSIONS.ACCOUNTING_PERIOD_MANAGE,
      PERMISSIONS.ACCOUNTING_REPORTS_READ,
      PERMISSIONS.ACCOUNTING_REPORTS_EXPORT,
      PERMISSIONS.ACCOUNTING_BUDGET_READ,
      PERMISSIONS.ACCOUNTING_BUDGET_MANAGE,
      PERMISSIONS.BUSINESS_CONTACTS_READ,
      PERMISSIONS.BUSINESS_CONTACTS_MANAGE,
      PERMISSIONS.BUSINESS_INVOICES_READ,
      PERMISSIONS.BUSINESS_INVOICES_MANAGE,
      PERMISSIONS.BUSINESS_INVOICES_APPROVE,
      PERMISSIONS.BUSINESS_PAYMENTS_READ,
      PERMISSIONS.BUSINESS_PAYMENTS_MANAGE,
      PERMISSIONS.BUSINESS_PAYMENTS_APPROVE,
      PERMISSIONS.COMPLIANCE_VAT_READ,
      PERMISSIONS.COMPLIANCE_VAT_MANAGE,
      PERMISSIONS.COMPLIANCE_ZATCA_READ,
      PERMISSIONS.COMPLIANCE_ZATCA_MANAGE,
      PERMISSIONS.COMPLIANCE_ZAKAT_READ,
      PERMISSIONS.COMPLIANCE_ZAKAT_MANAGE,
      PERMISSIONS.COMPLIANCE_WHT_READ,
      PERMISSIONS.COMPLIANCE_WHT_MANAGE,
      PERMISSIONS.COMPLIANCE_GOSI_READ,
      PERMISSIONS.COMPLIANCE_GOSI_MANAGE,
      PERMISSIONS.COMPLIANCE_WPS_READ,
      PERMISSIONS.COMPLIANCE_WPS_MANAGE,
      PERMISSIONS.ADMIN_BRANCHES_READ,
      PERMISSIONS.ADMIN_COST_CENTERS_READ,
    ],
  },
  VIEWER: {
    name: 'Viewer',
    description: 'Read-only access to accounting data and reports.',
    permissions: [
      PERMISSIONS.ACCOUNTING_COA_READ,
      PERMISSIONS.ACCOUNTING_JOURNAL_READ,
      PERMISSIONS.ACCOUNTING_PERIOD_READ,
      PERMISSIONS.ACCOUNTING_REPORTS_READ,
      PERMISSIONS.ACCOUNTING_BUDGET_READ,
      PERMISSIONS.BUSINESS_CONTACTS_READ,
      PERMISSIONS.BUSINESS_INVOICES_READ,
      PERMISSIONS.BUSINESS_PAYMENTS_READ,
      PERMISSIONS.COMPLIANCE_VAT_READ,
      PERMISSIONS.COMPLIANCE_ZATCA_READ,
      PERMISSIONS.COMPLIANCE_ZAKAT_READ,
      PERMISSIONS.COMPLIANCE_WHT_READ,
      PERMISSIONS.ADMIN_BRANCHES_READ,
      PERMISSIONS.ADMIN_COST_CENTERS_READ,
    ],
  },
} as const;

export type DefaultRoleName = keyof typeof DEFAULT_ROLES;
